stages:
  - docker
  - deploy

docker_build:
    stage: docker
    image: docker:24
    services:
      - docker:24-dind
    variables:
      DOCKER_TLS_CERTDIR: ""
    script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
      - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      
deploy_prod:
    stage: deploy
    image: curlimages/curl:latest  
    script:
      - curl -X POST "URL_DO_WEBHOOK_DO_PORTAINER"    
    only:
      - main

      